"DietaryService": [{
	"key": "30",
	"iconSource": "SimpleLineIcons",
	"iconName": "calendar",
	"iconSize": 22,
	"title": "就餐记录",
	"url": "EatRecord",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "23",
	"iconSource": "Feather",
	"iconName": "package",
	"iconSize": 22,
	"title": "菜品库",
	"url": "FoodLibrary",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "24",
	"iconSource": "MaterialCommunityIcons",
	"iconName": "human-greeting",
	"iconSize": 25,
	"title": "厨师展示",
	"url": "CookDisplay",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "25",
	"iconSource": "MaterialCommunityIcons",
	"iconName": "food",
	"iconSize": 26,
	"title": "当日菜品",
	"url": "TodayFood",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "27",
	"iconSource": "MaterialIcons",
	"iconName": "photo-size-select-small",
	"iconSize": 26,
	"title": "剩余菜量",
	"url": "SurplusFood",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "28",
	"iconSource": "Entypo",
	"iconName": "credit-card",
	"iconSize": 24,
	"title": "卡业务审核",
	"url": "VerifyCard",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "29",
	"iconSource": "FontAwesome",
	"iconName": "edit",
	"iconSize": 24,
	"title": "膳食业务审核",
	"url": "VerifyOrderEat",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
},
{
	"key": "32",
	"iconSource": "MaterialCommunityIcons",
	"iconName": "human-male-female",
	"iconSize": 24,
	"title": "人流量",
	"url": "ManFlowrate",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}],
"HouseManage": [{
	"key": "11",
	"iconSource": "Ionicons",
	"iconName": "md-build",
	"iconSize": 25,
	"title": "维管报修",
	"url": "ManageRepair",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "12",
	"iconSource": "Feather",
	"iconName": "book",
	"iconSize": 25,
	"title": "政策法规",
	"url": "Web",
	"params": {},
	"isWebView": true,
	"webViewParams": {
		"Title": "政策法规",
		"showHeader": true,
		"url": "http://m.zhihuilixia.com/cms/categories/%E6%94%BF%E7%AD%96%E6%B3%95%E8%A7%84"
	}
}, {
	"key": "13",
	"iconSource": "MaterialIcons",
	"iconName": "business",
	"iconSize": 25,
	"title": "楼层指引",
	"url": "Web",
	"params": {},
	"isWebView": true,
	"webViewParams": {
		"Title": "楼层指引",
		"showHeader": true,
		"url": "http://m.zhihuilixia.com/cms/2018/05/15/%E6%A5%BC%E5%B1%82%E6%8C%87%E5%BC%95"
	}
}
, {
	"key": "14",
	"iconSource": "MaterialIcons",
	"iconName": "record-voice-over",
	"iconSize": 25,
	"title": "投诉建议",
	"url": "Complaint",
	"params": {
		"service_type": "maintenance"
	},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "15",
	"iconSource": "Ionicons",
	"iconName": "ios-settings",
	"iconSize": 25,
	"title": "设备保养",
	"url": "DeviceMaintain",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "16",
	"iconSource": "Feather",
	"iconName": "file-text",
	"iconSize": 25,
	"title": "保养日志",
	"url": "MaintainLogs",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "16",
	"iconSource": "FontAwesome",
	"iconName": "calendar-check-o",
	"iconSize": 25,
	"title": "签到签退",
	"url": "SignIn",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "17",
	"iconSource": "SimpleLineIcons",
	"iconName": "calendar",
	"iconSize": 20,
	"title": "请假调休",
	"url": "Leave",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "18",
	"iconSource": "Feather",
	"iconName": "check-square",
	"iconSize": 25,
	"title": "报修受理",
	"url": "ManageRepairVerify",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "18",
	"iconSource": "Feather",
	"iconName": "user-check",
	"iconSize": 25,
	"title": "请假审核",
	"url": "VerifyLeave",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}],
"Parking": [{
	"key": "19",
	"iconSource": "MaterialCommunityIcons",
	"iconName": "parking",
	"iconSize": 20,
	"title": "停车预约",
	"url": "OrderParking",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "20",
	"iconSource": "MaterialCommunityIcons",
	"iconName": "account-plus-outline",
	"iconSize": 25,
	"title": "访客登记",
	"url": "VisitorRegistration",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "21",
	"iconSource": "FontAwesome",
	"iconName": "file-text-o",
	"iconSize": 18,
	"title": "预约受理",
	"url": "ReservationAudit",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "22",
	"iconSource": "MaterialCommunityIcons",
	"iconName": "home-outline",
	"iconSize": 30,
	"title": "我的车库",
	"url": "CarStore",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}, {
	"key": "31",
	"iconSource": "FontAwesome",
	"iconName": "car",
	"iconSize": 20,
	"title": "车辆查询",
	"url": "CarSearch",
	"params": {},
	"isWebView": false,
	"webViewParams": {}
}]

[{
	"floor": "1楼",
	"url": "http://m.zhihuilixia.com/cms/2018/05/15/%E6%A5%BC%E5%B1%82%E6%8C%87%E5%BC%95/1.jpg"
},
{
	"floor": "2楼",
	"url": "http://m.zhihuilixia.com/cms/2018/05/15/%E6%A5%BC%E5%B1%82%E6%8C%87%E5%BC%95/2.jpg"
},
{
	"floor": "3楼",
	"url": "http://m.zhihuilixia.com/cms/2018/05/15/%E6%A5%BC%E5%B1%82%E6%8C%87%E5%BC%95/3.jpg"
},
{
	"floor": "4楼",
	"url": "http://m.zhihuilixia.com/cms/2018/05/15/%E6%A5%BC%E5%B1%82%E6%8C%87%E5%BC%95/4.jpg"
}]